"""
Generate C++ sources that embed all .tflite models under a directory.

Outputs:
  - <out_dir>/models.h
  - <out_dir>/models.cc
"""

import argparse
import os
import re
from pathlib import Path

import tflite


def sanitize(name):
    """Return a C identifier derived from a filename stem."""
    cleaned = re.sub(r"[^A-Za-z0-9_]", "_", name)
    if cleaned and cleaned[0].isdigit():
        cleaned = f"_{cleaned}"
    return cleaned


def format_byte_array(data, width=12):
    """Format bytes as comma separated hex literals with indentation."""
    hex_bytes = [f"0x{b:02x}" for b in data]
    lines = []
    for i in range(0, len(hex_bytes), width):
        chunk = ", ".join(hex_bytes[i : i + width])
        lines.append(f"  {chunk},")
    return "\n".join(lines)


def discover_models(models_dir):
    """Return sorted list of (stem, path) pairs for .tflite models."""
    pairs = []
    for path in sorted(models_dir.glob("*.tflite")):
        pairs.append((path.stem, path))
    if not pairs:
        raise SystemExit(f"No .tflite models found in {models_dir}")
    return pairs


def to_camel(name):
    """Convert TFLite op name (e.g., CONV_2D) into CamelCase (Conv2D)."""
    parts = name.lower().split("_")
    return "".join(p.title() for p in parts)


def get_op_names(model_buf):
    """Return sorted builtin op names (as strings) used by the model."""
    model = tflite.Model.GetRootAsModel(model_buf, 0)

    opcode_map = {}
    for i in range(model.OperatorCodesLength()):
        op_code = model.OperatorCodes(i)
        opcode_map[i] = tflite.opcode2name(op_code.BuiltinCode())

    found_ops = set()
    for i in range(model.SubgraphsLength()):
        subgraph = model.Subgraphs(i)
        for j in range(subgraph.OperatorsLength()):
            op = subgraph.Operators(j)
            opcode_index = op.OpcodeIndex()
            found_ops.add(opcode_map[opcode_index])

    return sorted(found_ops)


def write_header(out_dir, models):
    header_path = out_dir / "models.h"
    macro_lines = ["#define TFLM_FOREACH_MODEL(M) \\"]
    for sanitized, original, _ in models:
        macro_lines.append(f"  M({sanitized}, \"{original}\") \\")
    # Drop trailing backslash on final line for cleaner preprocessor output.
    macro_lines[-1] = macro_lines[-1].rstrip(" \\")

    op_apply_macros = []
    for sanitized, _, ops in models:
        op_apply_macros.append(f"#define TFLM_APPLY_MODEL_OPS_{sanitized}(resolver) \\")
        for op in ops:
            op_apply_macros.append(f"  TF_LITE_ENSURE_STATUS((resolver).Add{op}()); \\")
        op_apply_macros[-1] = op_apply_macros[-1].rstrip(" \\")
        op_apply_macros.append(f"#define TFLM_MODEL_OP_COUNT_{sanitized} {len(ops)}")

    header_content = f"""// Generated by gen_models.py. Do not edit by hand.
#pragma once

#include <stddef.h>
#include <stdint.h>

{os.linesep.join(macro_lines)}

#define TFLM_DECLARE_MODEL(symbol, display_name) \\
  extern const unsigned char g_model_data_##symbol[]; \\
  extern const size_t g_model_data_##symbol##_len;
TFLM_FOREACH_MODEL(TFLM_DECLARE_MODEL)
#undef TFLM_DECLARE_MODEL

{os.linesep.join(op_apply_macros)}
"""
    header_path.write_text(header_content)


def write_source(out_dir, models):
    source_path = out_dir / "models.cc"

    array_defs = []
    for sanitized, _, data in models:
        array_defs.append(
            f"""alignas(16) const unsigned char g_model_data_{sanitized}[] = {{
{format_byte_array(data)}
}};
const size_t g_model_data_{sanitized}_len = sizeof(g_model_data_{sanitized});
"""
        )

    source_content = f"""// Generated by gen_models.py. Do not edit by hand.
#include "gen/models.h"

{os.linesep.join(array_defs)}
"""

    source_path.write_text(source_content)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--models_dir", required=True, type=Path)
    parser.add_argument("--out_dir", required=True, type=Path)
    args = parser.parse_args()

    models_dir = args.models_dir
    out_dir = args.out_dir
    out_dir.mkdir(parents=True, exist_ok=True)

    discovered = discover_models(models_dir)
    sanitized = []
    for stem, path in discovered:
        symbol = sanitize(stem)
        sanitized.append((symbol, stem, path))

    seen = {}
    for symbol, stem, _ in sanitized:
        if symbol in seen and seen[symbol] != stem:
            raise SystemExit(f"Sanitized names collide: {seen[symbol]} vs {stem}")
        seen[symbol] = stem

    models_bytes = []
    models_with_ops = []
    for symbol, stem, path in sanitized:
        data = path.read_bytes()
        ops = [to_camel(op_name) for op_name in get_op_names(data)]
        models_bytes.append((symbol, stem, data))
        models_with_ops.append((symbol, stem, ops))

    write_header(out_dir, models_with_ops)
    write_source(out_dir, models_bytes)


if __name__ == "__main__":
    main()
